In [17]:
import pandas as pd
ruta = r"C:\Users\walne\OneDrive\Documentos\Proyectos\Proyectomysql\proyect-sql\world_happiness_2015.csv"
df2015 = pd.read_csv(ruta, sep=";", decimal=",")

In [3]:
df2015.shape

(158, 10)

In [7]:
df2015.head()

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Switzerland,Western Europe,7.59,8.26,0.96,73,0.99,0.37,0.24
1,2,Iceland,Western Europe,7.56,7.70,1.00,73,0.94,0.55,0.74
2,3,Denmark,Western Europe,7.53,7.84,0.97,70,0.97,0.43,0.12
3,4,Norway,Western Europe,7.52,8.63,0.95,71,1.00,0.44,0.34
4,5,Canada,North America and ANZ,7.43,7.85,0.94,71,0.95,0.58,0.40

In [8]:
ruta2 = r"C:\Users\walne\OneDrive\Documentos\Proyectos\Proyectomysql\proyect-sql\world_happiness_2024.csv"
df2024 = pd.read_csv(ruta2, sep=";", decimal=",")

In [6]:
df2024.head()

,Ranking,Country,Regional indicator,Ladder score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,140,Afghanistan,South Asia,1.7210,2.93451,0.00000,62,0.00000,0.22638,0.15383
1,86,Albania,Central and Eastern Europe,5.3042,6.71748,0.57133,74,0.79892,0.34403,0.08517
2,84,Argelia,Sub-Saharan Africa,5.3635,6.18327,0.73652,72,0.28611,0.22771,0.34775
3,48,Argentina,Latin America and Caribbean,6.1881,7.29612,0.85449,73,0.78851,0.21822,0.13990
4,81,Armenia,Commonwealth of Independent States,5.4549,6.74410,0.71415,73,0.75317,0.12831,0.30090

In [61]:
from cleaning import renombrar_columna

df2024 = renombrar_columna(
    df2024,
    "Ladder score",
    "Happiness score"
)

In [11]:
df2024 = df2024.sort_values("GDP per capita", ascending=False)
df2024.head(20)

,Ranking,Country,Regional indicator,Ladder score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
76,8,Luxembourg,Western Europe,7.1219,10.00000,0.83799,77,0.92805,0.36347,0.75188
57,17,Ireland,Western Europe,6.8380,9.94539,0.85979,76,0.87756,0.51196,0.72707
113,30,Singapore,Southeast Asia,6.5228,9.89526,0.84207,78,0.86056,0.41990,1.00000
130,22,United Arab Emirates,Middle East and North Africa,6.7331,9.26467,0.72003,72,0.94401,0.52127,0.44914
121,9,Switzerland,Western Europe,7.0602,9.20463,0.88148,78,0.87934,0.43239,0.86525
99,7,Norway,Western Europe,7.3017,9.11908,0.93815,76,0.96762,0.55922,0.84146
132,23,United States,North America and ANZ,6.7248,9.05791,0.86094,72,0.67918,0.55708,0.29412
50,85,Hong Kong,East Asia,5.3164,8.91705,0.73273,81,0.56144,0.36619,0.69833
31,2,Denmark,Western Europe,7.5827,8.91278,0.94051,76,0.95298,0.50792,0.95358
93,6,Netherlands,Western Europe,7.3194,8.87942,0.90444,76,0.83986,0.61715,0.64757
6,14,Austria,Western Europe,6.9047,8.80752,0.82671,76,0.81399,0.53362,0.52956
52,3,Iceland,Western Europe,7.5251,8.78627,1.00000,77,0.94808,0.64455,0.31728
120,4,Sweden,Western Europe,7.3441,8.77425,0.92843,77,0.97097,0.55252,0.91078
44,24,Germany,Western Europe,6.7185,8.74242,0.85967,76,0.81064,0.43453,0.63956
9,16,Belgium,Western Europe,6.8942,8.72705,0.89106,76,0.84413,0.42531,0.54042
5,10,Australia,North America and ANZ,7.0569,8.66266,0.90385,76,0.87599,0.56188,0.56224
67,13,Kuwait,Middle East and North Africa,6.9514,8.61974,0.84357,75,0.95743,0.49779,0.29849
39,1,Finland,Western Europe,7.7407,8.61498,0.97268,76,0.99532,0.35347,0.94966
109,28,Saudi Arabia,Middle East and North Africa,6.5935,8.60725,0.84171,71,0.91172,0.28415,0.32685
122,31,Taiwan Province of China,East Asia,6.5035,8.60343,0.83257,75,0.75178,0.17043,0.35184

In [38]:
df2024["Ladder score"].dtype

dtype('float64')

In [24]:
from cleaning import redondear_floats

df2024 = redondear_floats(df2024, 2)

In [29]:
df2024.columns = df2024.columns.str.lower()

In [30]:
col = df[["Country"]]

In [28]:
col

         Country
0    Afghanistan
1        Albania
2        Argelia
3      Argentina
4        Armenia
..           ...
135    Venezuela
136      Vietnam
137        Yemen
138       Zambia
139     Zimbabwe

[140 rows x 1 columns]

In [31]:
df2024.head()

,ranking,country,regional indicator,ladder score,gdp per capita,social support,healthy life expectancy,freedom to make life choices,generosity,perceptions of corruption
76,8,Luxembourg,Western Europe,7.12,10.00,0.84,77,0.93,0.36,0.75
57,17,Ireland,Western Europe,6.84,9.95,0.86,76,0.88,0.51,0.73
113,30,Singapore,Southeast Asia,6.52,9.90,0.84,78,0.86,0.42,1.00
130,22,United Arab Emirates,Middle East and North Africa,6.73,9.26,0.72,72,0.94,0.52,0.45
121,9,Switzerland,Western Europe,7.06,9.20,0.88,78,0.88,0.43,0.87

In [20]:
!pip install pandas country_converter

Requirement already satisfied: pandas in C:\Users\walne\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (3.0.6)
Requirement already satisfied: country_converter in C:\Users\walne\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (1.3.2)
Requirement already satisfied: numpy>=2.3.3 in C:\Users\walne\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2.5.3)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\walne\AppData\Roaming\Python\Python314\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in C:\Users\walne\AppData\Local\Python\pythoncore-3.14-64\Lib\site-packages (from pandas) (2026.4)
Requirement already satisfied: six>=1.5 in C:\Users\walne\AppData\Roaming\Python\Python314\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [33]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

password = quote_plus("18708812")
engine = create_engine(f"mysql+pymysql://root:{18708812}@localhost:3306/proyectomysql")

In [35]:
df_pais["id_pais"] = ["P" + str(i).zfill(3) for i in range(1, len(df_pais) + 1)]

df_pais.to_sql("pais", con=engine, if_exists="append", index=False)

140