In [1]:
import requests
import pandas as pd

In [2]:
pip install pandas country_converter

Requirement already satisfied: pandas in c:\Users\Usuario\anaconda3\Lib\site-packages (3.0.3)
Requirement already satisfied: country_converter in c:\Users\Usuario\anaconda3\Lib\site-packages (1.3.2)
Requirement already satisfied: numpy>=2.3.3 in c:\Users\Usuario\anaconda3\Lib\site-packages (from pandas) (2.4.6)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\Users\Usuario\anaconda3\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: tzdata in c:\Users\Usuario\anaconda3\Lib\site-packages (from pandas) (2026.2)
Requirement already satisfied: six>=1.5 in c:\Users\Usuario\anaconda3\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

In [3]:
url1 = "https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.CD?format=json&per_page=20000&date=2015:2025"
api = requests.get(url1)

In [4]:
api.status_code

200

In [5]:
def limpiar_respuesta_api(api):
    datos_json = api.json()
    registros = datos_json[1]
    df = pd.DataFrame(registros)

    df['country_id'] = df['country'].apply(lambda x: x['id'] if isinstance(x, dict) else None)
    df['country_value'] = df['country'].apply(lambda x: x['value'] if isinstance(x, dict) else None)

    df = df.drop(columns=['indicator', 'country', 'obs_status', 'decimal'])
    columnas_ordenadas = ['country_id', 'country_value', 'date', 'value']
    df = df[columnas_ordenadas]
    df = df.rename(columns={
        'country_id': 'id_pais',
        'country_value': 'pais',
        'date': 'año',
        'value': 'gdp_per_capita'})
    
    df = df[df['año'].astype(str) == '2024']
    df = df.drop(columns=['año'])
    df = df.sort_values(by='gdp_per_capita', ascending=False)
    return df

df_pib_2024 = limpiar_respuesta_api(api)
df_pib_2024.head()
len(df_pib_2024)

265

In [6]:
df_pib_2024.head(10)

     id_pais               pais  gdp_per_capita
1805      LU         Luxembourg   156079.368561
2410      SG          Singapore   153161.175431
1552      IE            Ireland   140779.203379
1816      MO   Macao SAR, China   127144.298138
2278      QA              Qatar   126712.582876
760       BM            Bermuda   118727.973294
2146      NO             Norway   105657.033919
2597      CH        Switzerland    97467.744715
925       KY     Cayman Islands    92201.086358
837       BN  Brunei Darussalam    90009.891250

In [7]:
url2 = "https://api.worldbank.org/v2/country/all/indicator/EG.ELC.ACCS.ZS?format=json&per_page=20000&date=2015:2025"
inf_electrica = requests.get(url2)

In [8]:
inf_electrica.status_code

200

In [9]:
def limpiar_respuesta_api(inf_electrica):
    datos_json2 = inf_electrica.json()
    registros2 = datos_json2[1]
    df = pd.DataFrame(registros2)

    df['country_id'] = df['country'].apply(lambda x: x['id'] if isinstance(x, dict) else None)
    df['country_value'] = df['country'].apply(lambda x: x['value'] if isinstance(x, dict) else None)
    

    df = df.drop(columns=['indicator', 'country', 'obs_status', 'decimal', 'unit'])
    columnas_ordenadas = ['country_id', 'country_value', 'date', 'value']
    df = df[columnas_ordenadas]
    df = df.rename(columns={
        'country_id': 'id_pais',
        'country_value': 'pais',
        'date': 'año',
        'value': 'Acceso_inf_elect'})

    df = df[df['año'].astype(str) == '2024']
    df = df.drop(columns=['año'])
    df['Acceso_inf_elect'] = (df['Acceso_inf_elect'])
    df = df.sort_values(by='Acceso_inf_elect', ascending=False)


    return df

df_inf_elect2024 = limpiar_respuesta_api(inf_electrica) 
df_inf_elect2024.head()
len(df_inf_elect2024)

265

In [10]:
url3 = "https://api.worldbank.org/v2/country/all/indicator/SH.H2O.SMDW.ZS?format=json&per_page=20000&date=2015:2025"
inf_agua = requests.get(url3)
#población con acceso a servicios de agua potable gestionados de manera segura

In [11]:
inf_agua.status_code

200

In [12]:
def limpiar_respuesta_api(inf_agu):
    datos_json2 = inf_agu.json()
    registros3 = datos_json2[1]
    df = pd.DataFrame(registros3)

    df['country_id'] = df['country'].apply(lambda x: x['id'] if isinstance(x, dict) else None)
    df['country_value'] = df['country'].apply(lambda x: x['value'] if isinstance(x, dict) else None)
    

    df = df.drop(columns=['indicator', 'country', 'obs_status', 'decimal', 'unit'])
    columnas_ordenadas = ['country_id', 'country_value', 'date', 'value']
    df = df[columnas_ordenadas]
    df = df.rename(columns={
        'country_id': 'id_pais',
        'country_value': 'pais',
        'date': 'año',
        'value': 'Acceso_inf_agua'})

    df = df[df['año'].astype(str) == '2024']
    df = df.drop(columns=['año'])
    df['Acceso_inf_agua'] = (df['Acceso_inf_agua'])
    df = df.sort_values(by='Acceso_inf_agua', ascending=False)

    return df

df_inf_agua2024 = limpiar_respuesta_api(inf_agua) 
df_inf_agua2024.head(20)
len(df_inf_agua2024)

265

In [16]:
import pandas as pd
import country_converter as coco

In [17]:
df = pd.read_csv("world_happiness_2024.csv", sep=";", decimal=",")
df["id_pais"] = coco.convert(names=df["Country"], to="ISO2", not_found="NO ENCONTRADO")

Argelia not found in regex

In [18]:
print(df.loc[df["id_pais"] == "NO ENCONTRADO", "Country"].tolist())

['Argelia']

In [19]:
df.insert(0, "id_pais", df.pop("id_pais"))
df.to_csv("world_happiness_2024_con_id.csv", index=False, sep=";", decimal=",", encoding="utf-8-sig")
df

,id_pais,Ranking,Country,Regional indicator,Ladder score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,AF,140,Afghanistan,South Asia,1.7210,2.93451,0.00000,62,0.00000,0.22638,0.15383
1,AL,86,Albania,Central and Eastern Europe,5.3042,6.71748,0.57133,74,0.79892,0.34403,0.08517
2,NO ENCONTRADO,84,Argelia,Sub-Saharan Africa,5.3635,6.18327,0.73652,72,0.28611,0.22771,0.34775
3,AR,48,Argentina,Latin America and Caribbean,6.1881,7.29612,0.85449,73,0.78851,0.21822,0.13990
4,AM,81,Armenia,Commonwealth of Independent States,5.4549,6.74410,0.71415,73,0.75317,0.12831,0.30090
...,...,...,...,...,...,...,...,...,...,...,...
135,VE,78,Venezuela,Latin America and Caribbean,5.6067,0.00000,0.81740,70,0.59990,0.47969,0.14982
136,VN,54,Vietnam,Southeast Asia,6.0430,6.21579,0.78378,71,0.97594,0.23369,0.27818
137,YE,130,Yemen,Middle East and North Africa,3.5610,3.13606,0.79273,64,0.41974,0.19988,0.19678
138,ZM,131,Zambia,Sub-Saharan Africa,3.5024,4.19978,0.50041,63,0.84216,0.41825,0.19012
139,ZW,135,Zimbabwe,Sub-Saharan Africa,3.3411,3.49606,0.52587,62,0.56401,0.23983,0.22708

In [20]:
df.columns = df.columns.str.lower()

In [21]:
from sqlalchemy import create_engine
from urllib.parse import quote_plus

from getpass import getpass

password = quote_plus(getpass("Contraseña de MySQL: "))
engine = create_engine(f"mysql+pymysql://root:{password}@localhost:3306/proyectomysql")

In [23]:
df_pais = df[["id_pais", "country", "regional indicator"]].rename(columns={
    "regional indicator": "regional_indicator"
})

df_pais.to_sql("pais", con=engine, if_exists="append", index=False)

DatabaseError: Execution failed on sql 'INSERT INTO pais (id_pais, country, regional_indicator) VALUES (:id_pais, :country, :regional_indicator)': (pymysql.err.IntegrityError) (1062, "Duplicate entry 'AF' for key 'pais.PRIMARY'")
[SQL: INSERT INTO pais (id_pais, country, regional_indicator) VALUES (%(id_pais)s, %(country)s, %(regional_indicator)s)]
[parameters: [{'id_pais': 'AF', 'country': 'Afghanistan', 'regional_indicator': 'South Asia'}, {'id_pais': 'AL', 'country': 'Albania', 'regional_indicator': 'Central and Eastern Europe'}, {'id_pais': 'NO ENCONTRADO', 'country': 'Argelia', 'regional_indicator': 'Sub-Saharan Africa'}, {'id_pais': 'AR', 'country': 'Argentina', 'regional_indicator': 'Latin America and Caribbean'}, {'id_pais': 'AM', 'country': 'Armenia', 'regional_indicator': 'Commonwealth of Independent States'}, {'id_pais': 'AU', 'country': 'Australia', 'regional_indicator': 'North America and ANZ'}, {'id_pais': 'AT', 'country': 'Austria', 'regional_indicator': 'Western Europe'}, {'id_pais': 'AZ', 'country': 'Azerbaijan', 'regional_indicator': 'Commonwealth of Independent States'}  ... displaying 10 of 140 total bound parameter sets ...  {'id_pais': 'ZM', 'country': 'Zambia', 'regional_indicator': 'Sub-Saharan Africa'}, {'id_pais': 'ZW', 'country': 'Zimbabwe', 'regional_indicator': 'Sub-Saharan Africa'}]]
(Background on this error at: https://sqlalche.me/e/21/gkpj)

In [24]:
from sqlalchemy import text

In [25]:
df_pib = df_pib_2024[["id_pais", "gdp_per_capita"]].rename(columns={
    "gdp_per_capita": "pib"})

In [26]:
with engine.connect() as conexion:
    try:
        conexion.execute(text("SET FOREIGN_KEY_CHECKS = 0;"))
        df_pib.to_sql("pib_bm", con=conexion, if_exists="append", index=False)
        conexion.execute(text("SET FOREIGN_KEY_CHECKS = 1;"))
        conexion.commit()
        
    except Exception as e:
        try:
            conexion.execute(text("SET FOREIGN_KEY_CHECKS = 1;"))
            conexion.rollback()
        except:
            pass

In [27]:
df_ranking = df[["id_pais", "ranking", "ladder score"]].rename(columns={
    "ladder score": "happiness_score"
})

df_ranking.to_sql("ranking", con=engine, if_exists="append", index=False)

DatabaseError: Execution failed on sql 'INSERT INTO ranking (id_pais, ranking, happiness_score) VALUES (:id_pais, :ranking, :happiness_score)': (pymysql.err.IntegrityError) (1062, "Duplicate entry 'AF' for key 'ranking.PRIMARY'")
[SQL: INSERT INTO ranking (id_pais, ranking, happiness_score) VALUES (%(id_pais)s, %(ranking)s, %(happiness_score)s)]
[parameters: [{'id_pais': 'AF', 'ranking': 140, 'happiness_score': 1.721}, {'id_pais': 'AL', 'ranking': 86, 'happiness_score': 5.3042}, {'id_pais': 'NO ENCONTRADO', 'ranking': 84, 'happiness_score': 5.3635}, {'id_pais': 'AR', 'ranking': 48, 'happiness_score': 6.1881}, {'id_pais': 'AM', 'ranking': 81, 'happiness_score': 5.4549}, {'id_pais': 'AU', 'ranking': 10, 'happiness_score': 7.0569}, {'id_pais': 'AT', 'ranking': 14, 'happiness_score': 6.9047}, {'id_pais': 'AZ', 'ranking': 99, 'happiness_score': 4.8934}  ... displaying 10 of 140 total bound parameter sets ...  {'id_pais': 'ZM', 'ranking': 131, 'happiness_score': 3.5024}, {'id_pais': 'ZW', 'ranking': 135, 'happiness_score': 3.3411}]]
(Background on this error at: https://sqlalche.me/e/21/gkpj)

In [28]:
df_social = df[["id_pais", "social support", "freedom to make life choices",
                "generosity", "perceptions of corruption"]].rename(columns={
    "social support": "social_support",
    "freedom to make life choices": "freedom_to_make_life_choices",
    "perceptions of corruption": "perceptions_of_corruption"
})

df_social.to_sql("social", con=engine, if_exists="append", index=False)

DatabaseError: Execution failed on sql 'INSERT INTO social (id_pais, social_support, freedom_to_make_life_choices, generosity, perceptions_of_corruption) VALUES (:id_pais, :social_support, :freedom_to_make_life_choices, :generosity, :perceptions_of_corruption)': (pymysql.err.IntegrityError) (1062, "Duplicate entry 'AF' for key 'social.PRIMARY'")
[SQL: INSERT INTO social (id_pais, social_support, freedom_to_make_life_choices, generosity, perceptions_of_corruption) VALUES (%(id_pais)s, %(social_support)s, %(freedom_to_make_life_choices)s, %(generosity)s, %(perceptions_of_corruption)s)]
[parameters: [{'id_pais': 'AF', 'social_support': 0.0, 'freedom_to_make_life_choices': 0.0, 'generosity': 0.22638, 'perceptions_of_corruption': 0.15383}, {'id_pais': 'AL', 'social_support': 0.57133, 'freedom_to_make_life_choices': 0.79892, 'generosity': 0.34403, 'perceptions_of_corruption': 0.08517}, {'id_pais': 'NO ENCONTRADO', 'social_support': 0.73652, 'freedom_to_make_life_choices': 0.28611, 'generosity': 0.22771, 'perceptions_of_corruption': 0.34775}, {'id_pais': 'AR', 'social_support': 0.85449, 'freedom_to_make_life_choices': 0.78851, 'generosity': 0.21822, 'perceptions_of_corruption': 0.1399}, {'id_pais': 'AM', 'social_support': 0.71415, 'freedom_to_make_life_choices': 0.75317, 'generosity': 0.12831, 'perceptions_of_corruption': 0.3009}, {'id_pais': 'AU', 'social_support': 0.90385, 'freedom_to_make_life_choices': 0.87599, 'generosity': 0.56188, 'perceptions_of_corruption': 0.56224}, {'id_pais': 'AT', 'social_support': 0.82671, 'freedom_to_make_life_choices': 0.81399, 'generosity': 0.53362, 'perceptions_of_corruption': 0.52956}, {'id_pais': 'AZ', 'social_support': 0.54171, 'freedom_to_make_life_choices': 0.77392, 'generosity': 0.27835, 'perceptions_of_corruption': 0.34637}  ... displaying 10 of 140 total bound parameter sets ...  {'id_pais': 'ZM', 'social_support': 0.50041, 'freedom_to_make_life_choices': 0.84216, 'generosity': 0.41825, 'perceptions_of_corruption': 0.19012}, {'id_pais': 'ZW', 'social_support': 0.52587, 'freedom_to_make_life_choices': 0.56401, 'generosity': 0.23983, 'perceptions_of_corruption': 0.22708}]]
(Background on this error at: https://sqlalche.me/e/21/gkpj)

In [29]:
df_inf_agua2024.head()

     id_pais                  pais  Acceso_inf_agua
1959      MC                Monaco            100.0
1486      HU               Hungary            100.0
1475      HK  Hong Kong SAR, China            100.0
1695      KW                Kuwait            100.0
1783      LI         Liechtenstein            100.0

In [30]:
df_inf_elect2024.tail()

     id_pais            pais  Acceso_inf_elect
947       TD            Chad              13.4
2487      SS     South Sudan               5.4
375       XY  Not classified               NaN
562       AS  American Samoa               NaN
1684      XK          Kosovo               NaN

In [31]:
print(df_inf_agua2024.columns.tolist())
print(df_inf_elect2024.columns.tolist())

['id_pais', 'pais', 'Acceso_inf_agua']
['id_pais', 'pais', 'Acceso_inf_elect']

In [32]:
df_final = df_inf_agua2024.merge(
    df_inf_elect2024,
    on=['id_pais', 'pais'],
    how='inner'
)

df_final

    id_pais                  pais  Acceso_inf_agua  Acceso_inf_elect
0        MC                Monaco            100.0             100.0
1        HU               Hungary            100.0             100.0
2        HK  Hong Kong SAR, China            100.0             100.0
3        KW                Kuwait            100.0             100.0
4        LI         Liechtenstein            100.0             100.0
..      ...                   ...              ...               ...
260      TR               Turkiye              NaN             100.0
261      UY               Uruguay              NaN             100.0
262      VE         Venezuela, RB              NaN             100.0
263      YE           Yemen, Rep.              NaN              86.3
264      ZM                Zambia              NaN              53.6

[265 rows x 4 columns]

In [33]:
df_final.tail()

    id_pais           pais  Acceso_inf_agua  Acceso_inf_elect
260      TR        Turkiye              NaN             100.0
261      UY        Uruguay              NaN             100.0
262      VE  Venezuela, RB              NaN             100.0
263      YE    Yemen, Rep.              NaN              86.3
264      ZM         Zambia              NaN              53.6

In [34]:
print(df_final.columns.tolist())

['id_pais', 'pais', 'Acceso_inf_agua', 'Acceso_inf_elect']

In [35]:
df_infra = df_final[["id_pais", "Acceso_inf_elect", "Acceso_inf_agua"]].rename(columns={
    "Acceso_inf_elect": "acceso_electrico",
    "Acceso_inf_agua": "acceso_agua"
})

In [36]:
ids_pais = pd.read_sql("SELECT id_pais FROM pais", con=engine)
print(df_infra[~df_infra["id_pais"].isin(ids_pais["id_pais"])])

    id_pais  acceso_electrico  acceso_agua
0        MC             100.0   100.000000
4        LI             100.0   100.000000
5        MO             100.0   100.000000
9        GI             100.0   100.000000
10       SM             100.0    99.999996
..      ...               ...          ...
254      LC             100.0          NaN
255      VC             100.0          NaN
256      SD              66.0          NaN
257      SY              89.3          NaN
259      TL              94.3          NaN

[127 rows x 3 columns]

In [37]:
print(df_final["id_pais"].duplicated().sum())

0

In [38]:
ids_pais = pd.read_sql("SELECT id_pais FROM pais", con=engine)

faltan = df_final[~df_final["id_pais"].isin(ids_pais["id_pais"])]
print(len(faltan))
print(faltan["id_pais"].tolist())

127
['MC', 'LI', 'MO', 'GI', 'SM', 'IM', 'PR', 'BH', 'VI', 'XU', 'NC', 'MF', 'XD', 'QA', 'TM', 'GU', 'BY', 'Z7', 'OM', 'PW', 'AD', 'AS', 'PF', 'T7', '7E', 'XF', 'MP', 'PS', 'T2', 'ZJ', 'XJ', 'XT', '8S', 'T5', 'Z4', '1W', 'ZT', 'TT', 'XN', 'DZ', 'GY', 'ZQ', 'BT', 'TJ', 'SC', 'XQ', 'T3', 'WS', 'SR', 'TC', 'FJ', 'XI', 'XG', 'XH', 'ST', 'ZF', 'XM', 'ZG', 'T6', 'ZH', 'ZI', 'TO', 'GW', 'VU', 'NR', 'KI', 'TV', 'CF', '1A', 'S3', 'B8', 'V2', '4E', 'T4', 'XC', 'EU', 'XE', 'V3', 'XL', 'XO', 'XP', 'XY', 'OE', 'S4', 'S2', 'V4', 'V1', 'S1', 'AO', 'AG', 'AW', 'BS', 'BB', 'BZ', 'BM', 'VG', 'BN', 'BI', 'CV', 'KY', 'JG', 'CU', 'CW', 'DJ', 'DM', 'GQ', 'ER', 'FO', 'GL', 'GD', 'HT', 'KP', 'MV', 'MH', 'FM', 'PG', 'RW', 'SX', 'SB', 'SO', 'SS', 'KN', 'LC', 'VC', 'SD', 'SY', 'TL']

In [39]:
df_infra = df_infra[df_infra["id_pais"].isin(ids_pais["id_pais"])]

df_infra.to_sql("infraestructura", con=engine, if_exists="append", index=False)

DatabaseError: Execution failed on sql 'INSERT INTO infraestructura (id_pais, acceso_electrico, acceso_agua) VALUES (:id_pais, :acceso_electrico, :acceso_agua)': (pymysql.err.IntegrityError) (1062, "Duplicate entry 'HU' for key 'infraestructura.PRIMARY'")
[SQL: INSERT INTO infraestructura (id_pais, acceso_electrico, acceso_agua) VALUES (%(id_pais)s, %(acceso_electrico)s, %(acceso_agua)s)]
[parameters: [{'id_pais': 'HU', 'acceso_electrico': 100.0, 'acceso_agua': 100.0}, {'id_pais': 'HK', 'acceso_electrico': 100.0, 'acceso_agua': 100.0}, {'id_pais': 'KW', 'acceso_electrico': 100.0, 'acceso_agua': 100.0}, {'id_pais': 'SG', 'acceso_electrico': 100.0, 'acceso_agua': 100.0}, {'id_pais': 'NZ', 'acceso_electrico': 100.0, 'acceso_agua': 100.0}, {'id_pais': 'IS', 'acceso_electrico': 100.0, 'acceso_agua': 100.0}, {'id_pais': 'NL', 'acceso_electrico': 100.0, 'acceso_agua': 99.9595063956065}, {'id_pais': 'DK', 'acceso_electrico': 100.0, 'acceso_agua': 99.9188271389611}  ... displaying 10 of 138 total bound parameter sets ...  {'id_pais': 'YE', 'acceso_electrico': 86.3, 'acceso_agua': None}, {'id_pais': 'ZM', 'acceso_electrico': 53.6, 'acceso_agua': None}]]
(Background on this error at: https://sqlalche.me/e/21/gkpj)

In [ ]:
print()