In [9]:
import requests
import pandas as pd

In [10]:
url1 = "https://api.worldbank.org/v2/country/all/indicator/NY.GDP.PCAP.PP.CD?format=json&per_page=20000&date=2015:2025"
api = requests.get(url1)

In [11]:
api.status_code

200

In [18]:
def limpiar_respuesta_api(api):
    datos_json = api.json()
    registros = datos_json[1]
    df = pd.DataFrame(registros)

    df['indicator_id'] = df['indicator'].apply(lambda x: x['id'] if isinstance(x, dict) else None)
    df['country_id'] = df['country'].apply(lambda x: x['id'] if isinstance(x, dict) else None)
    df['country_value'] = df['country'].apply(lambda x: x['value'] if isinstance(x, dict) else None)

    df = df.drop(columns=['indicator', 'country', 'obs_status', 'decimal'])
    columnas_ordenadas = ['country_id', 'country_value', 'date', 'value', 'indicator_id']
    df = df[columnas_ordenadas]

    df = df.rename(columns={
        'country_id': 'id_pais',
        'country_value': 'pais',
        'date': 'año',
        'value': 'gdp_per_capita',
        'indicator_id': 'id_indicador'})
    return df

In [19]:
df_pib = limpiar_respuesta_api(api)
df_pib.head()

,id_pais,pais,año,gdp_per_capita,id_indicador
0,ZH,Africa Eastern and Southern,2025,4840.265200,NY.GDP.PCAP.PP.CD
1,ZH,Africa Eastern and Southern,2024,4635.125049,NY.GDP.PCAP.PP.CD
2,ZH,Africa Eastern and Southern,2023,4496.744898,NY.GDP.PCAP.PP.CD
3,ZH,Africa Eastern and Southern,2022,4359.591407,NY.GDP.PCAP.PP.CD
4,ZH,Africa Eastern and Southern,2021,4022.277659,NY.GDP.PCAP.PP.CD

In [22]:
def filtrar_por_años(df_pib):
    df_pib['año'] = df_pib['año'].astype(str)
    df_filtrado = df_pib[df_pib['año'].isin(['2015', '2024'])]

    return df_filtrado

In [24]:
df_pib_filtrado = filtrar_por_años(df_pib)
df_pib_filtrado.head()

,id_pais,pais,año,gdp_per_capita,id_indicador
1,ZH,Africa Eastern and Southern,2024,4635.125049,NY.GDP.PCAP.PP.CD
10,ZH,Africa Eastern and Southern,2015,3539.428265,NY.GDP.PCAP.PP.CD
12,ZI,Africa Western and Central,2024,6840.333882,NY.GDP.PCAP.PP.CD
21,ZI,Africa Western and Central,2015,5063.905375,NY.GDP.PCAP.PP.CD
23,1A,Arab World,2024,18963.718872,NY.GDP.PCAP.PP.CD