C:\Users\walne\AppData\Roaming\Microsoft\Office\Recent\world_happiness_2015.LNK
C:\Users\walne\AppData\Roaming\Microsoft\Office\Recent\world_happiness_2024.LNK
C:\Users\walne\AppData\Roaming\Microsoft\Windows\Recent\world_happiness_2015.lnk
C:\Users\walne\AppData\Roaming\Microsoft\Windows\Recent\world_happiness_2024.lnk
C:\Users\walne\Downloads\world_happiness_2015.csv
C:\Users\walne\Downloads\world_happiness_2024
C:\Users\walne\Downloads\world_happiness_2024 (1).csv
C:\Users\walne\Downloads\world_happiness_2024.csv
C:\Users\walne\OneDrive\Documentos\Proyectos\Proyectomysql\proyect-sql\world_happiness_2015.csv
C:\Users\walne\OneDrive\Documentos\Proyectos\Proyectomysql\proyect-sql\world_happiness_2024.csv

In [13]:
import pandas as pd
ruta = r"C:\Users\walne\OneDrive\Documentos\Proyectos\Proyectomysql\proyect-sql\world_happiness_2015.csv"
df2015 = pd.read_csv(ruta, sep=";", decimal=",")

In [14]:
df2015.shape

(158, 10)

In [16]:
df2015.head()

,Ranking,Country,Regional indicator,Happiness score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,1,Switzerland,Western Europe,7.59,8.26,0.96,73,0.99,0.37,0.24
1,2,Iceland,Western Europe,7.56,7.70,1.00,73,0.94,0.55,0.74
2,3,Denmark,Western Europe,7.53,7.84,0.97,70,0.97,0.43,0.12
3,4,Norway,Western Europe,7.52,8.63,0.95,71,1.00,0.44,0.34
4,5,Canada,North America and ANZ,7.43,7.85,0.94,71,0.95,0.58,0.40

In [17]:
ruta2 = r"C:\Users\walne\OneDrive\Documentos\Proyectos\Proyectomysql\proyect-sql\world_happiness_2024.csv"
df2024 = pd.read_csv(ruta2, sep=";", decimal=",")

In [19]:
df2024.head()

,Ranking,Country,Regional indicator,Ladder score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
0,140,Afghanistan,South Asia,1.7210,2.93451,0.00000,62,0.00000,0.22638,0.15383
1,86,Albania,Central and Eastern Europe,5.3042,6.71748,0.57133,74,0.79892,0.34403,0.08517
2,84,Argelia,Sub-Saharan Africa,5.3635,6.18327,0.73652,72,0.28611,0.22771,0.34775
3,48,Argentina,Latin America and Caribbean,6.1881,7.29612,0.85449,73,0.78851,0.21822,0.13990
4,81,Armenia,Commonwealth of Independent States,5.4549,6.74410,0.71415,73,0.75317,0.12831,0.30090

In [22]:
df2024 = df2024.sort_values("Ranking", ascending=True)
df2024.head()

,Ranking,Country,Regional indicator,Ladder score,GDP per capita,Social support,Healthy life expectancy,Freedom to make life choices,Generosity,Perceptions of corruption
39,1,Finland,Western Europe,7.7407,8.61498,0.97268,76,0.99532,0.35347,0.94966
31,2,Denmark,Western Europe,7.5827,8.91278,0.94051,76,0.95298,0.50792,0.95358
52,3,Iceland,Western Europe,7.5251,8.78627,1.00000,77,0.94808,0.64455,0.31728
120,4,Sweden,Western Europe,7.3441,8.77425,0.92843,77,0.97097,0.55252,0.91078
58,5,Israel,Middle East and North Africa,7.3411,8.42288,0.93583,78,0.74301,0.38224,0.33528